export const cargoModuleCatalog = [
  {
    id: 'gp',
    route: 'gp',
    name: 'Ерөнхий тохиргоо',
    name2: 'General settings',
    description: 'Organization, branch, action registry, dictionary, tariff and system logs.',
    actions: [
      { code: 'gen0010', name: 'Menu tree' },
      { code: 'gen0020', name: 'Organizations' },
      { code: 'gen0030', name: 'Branches' },
      { code: 'gen0040', name: 'Action registry' },
      { code: 'gen0050', name: 'Module list' },
      { code: 'gen0060', name: 'Dictionaries' },
      { code: 'gen0070', name: 'Dictionary options' },
      { code: 'gen0080', name: 'Sequences' },
      { code: 'gen0090', name: 'Suspensions' },
      { code: 'gen0100', name: 'Provider configs' },
      { code: 'gen0110', name: 'Response codes' },
      { code: 'gen0120', name: 'Whitelabel' },
      { code: 'gen0130', name: 'Mail configs' },
      { code: 'gen0140', name: 'Cargo service types' },
      { code: 'gen0150', name: 'Cargo tariffs' },
      { code: 'gen0160', name: 'Cargo service fees' },
      { code: 'gen0170', name: 'System jobs' },
      { code: 'gen0180', name: 'Permission matrix' },
      { code: 'gen0190', name: 'File assets' },
      { code: 'gen0200', name: 'Photo assets' },
      { code: 'gen0210', name: 'User delegates' },
      { code: 'gen0220', name: 'Audit logs' },
      { code: 'gen0230', name: 'Request logs' },
      { code: 'gen0240', name: 'Change logs' },
      { code: 'gen0250', name: 'Error logs' },
      { code: 'gen0260', name: 'Failed jobs' },
      { code: 'gen0270', name: 'Email logs' },
    ],
  },
  {
    id: 'ad',
    route: 'ad',
    name: 'Админ',
    name2: 'Administration',
    description: 'Users, roles, operators, notifications, automation and receipt configs.',
    actions: [
      { code: 'adm0010', name: 'User list' },
      { code: 'adm0020', name: 'Role list' },
      { code: 'adm0030', name: 'User roles' },
      { code: 'adm0040', name: 'Secret policies' },
      { code: 'adm0050', name: 'Report permissions' },
      { code: 'adm0060', name: 'Operators' },
      { code: 'adm0070', name: 'Notifications' },
      { code: 'adm0080', name: 'Notification templates' },
      { code: 'adm0090', name: 'Notification outbox' },
      { code: 'adm0100', name: 'Automation rules' },
      { code: 'adm0110', name: 'Automation runs' },
      { code: 'adm0120', name: 'Receipt configs' },
      { code: 'adm0130', name: 'Receipt logs' },
      { code: 'adm0140', name: 'Settlement accounts' },
      { code: 'adm0150', name: 'Email blacklist' },
    ],
  },
  {
    id: 'ap',
    route: 'ap',
    name: 'Аппликейшн',
    name2: 'Application',
    description: 'Backoffice auth and customer portal foundation.',
    actions: [
      { code: 'app0010', name: 'Backoffice login', samplePayload: { email: '', password: '' } },
      { code: 'app0020', name: 'Backoffice bootstrap' },
      { code: 'app0030', name: 'Backoffice logout' },
      { code: 'app0040', name: 'Portal profiles' },
      { code: 'app0050', name: 'Customer portal users' },
      { code: 'app0060', name: 'Portal services' },
      { code: 'app0070', name: 'Portal notifications' },
      { code: 'app0080', name: 'FAQ' },
      { code: 'app0090', name: 'Private resources' },
      { code: 'app0100', name: 'Customer contracts' },
      { code: 'app0110', name: 'Stopped services' },
      { code: 'app0120', name: 'Portal access tokens' },
    ],
  },
  {
    id: 'cr',
    route: 'cr',
    name: 'Харилцагч',
    name2: 'Customer',
    description: 'Customer registry, contacts, documents, billing and delivery preferences.',
    actions: [
      { code: 'cus0010', name: 'Customer list' },
      { code: 'cus0020', name: 'Customer addresses' },
      { code: 'cus0030', name: 'Customer contacts' },
      { code: 'cus0040', name: 'Customer documents' },
      { code: 'cus0050', name: 'Customer messages' },
      { code: 'cus0060', name: 'Customer relationships' },
      { code: 'cus0070', name: 'Customer credentials' },
      { code: 'cus0080', name: 'Customer stakeholders' },
      { code: 'cus0090', name: 'Customer billing accounts' },
      { code: 'cus0100', name: 'Delivery preferences' },
      { code: 'cus0110', name: 'Customer batch imports' },
    ],
  },
  {
    id: 'ca',
    route: 'ca',
    name: 'Карго',
    name2: 'Cargo',
    description: 'Cargo dashboard and shipment operations.',
    actions: [
      { code: 'car0010', name: 'Cargo dashboard' },
      { code: 'car0020', name: 'Shipment list' },
    ],
  },
  {
    id: 'pos',
    route: 'pos',
    name: 'POS',
    name2: 'POS',
    description: 'Point-of-sale dashboard and sale foundation.',
    actions: [
      { code: 'pos0010', name: 'POS dashboard' },
    ],
  },
  {
    id: 're',
    route: 're',
    name: 'Тайлан',
    name2: 'Reports',
    description: 'Report builder, datasets, exports and run logs.',
    actions: [
      { code: 'rep0010', name: 'Report templates' },
      { code: 'rep0020', name: 'Report datasets' },
      { code: 'rep0030', name: 'Report fields' },
      { code: 'rep0040', name: 'Report contents' },
      { code: 'rep0050', name: 'Report dimensions' },
      { code: 'rep0060', name: 'Report parameters' },
      { code: 'rep0070', name: 'Report parameter options' },
      { code: 'rep0080', name: 'Report exports' },
      { code: 'rep0090', name: 'Report run logs' },
    ],
  },
  {
    id: 'gl',
    route: 'gl',
    name: 'Ledger',
    name2: 'Ledger',
    description: 'Cargo operational ledger and posting setup.',
    actions: [
      { code: 'led0010', name: 'Ledger account groups' },
      { code: 'led0020', name: 'Ledger accounts' },
      { code: 'led0030', name: 'Ledger charts' },
      { code: 'led0040', name: 'Ledger inquiry' },
      { code: 'led0050', name: 'Ledger transactions' },
      { code: 'led0060', name: 'Posting rules' },
      { code: 'led0070', name: 'Ledger report configs' },
      { code: 'led0080', name: 'Ledger report columns' },
      { code: 'led0090', name: 'Ledger report runs' },
    ],
  },
]

export const cargoModuleByRoute = Object.fromEntries(cargoModuleCatalog.map((module) => [module.route, module]))
export const cargoModuleById = Object.fromEntries(cargoModuleCatalog.map((module) => [module.id, module]))

export const getCargoModuleByRoute = (route) => cargoModuleByRoute[route]
export const getCargoModuleById = (id) => cargoModuleById[id]
